### ISSUE TITLE
Add Purebasic

### ISSUE THREAD

**Issue by endo64** [JohnBlood/awesome-basic#1]
> PureBasic is a modern BASIC programming language. The key features of PureBasic are portability (Windows, Linux and OS X supported with the same source code), the production of very fast and optimized native 32-bit or 64-bit executables and, of course, the very simple BASIC language syntax. PureBasic has been created for the beginner and expert alike. We have put a lot of effort into its conception to produce a fast, reliable system and friendly BASIC compiler.

> Despite its beginner-friendly syntax, the possibilities are endless with PureBasic's advanced features such as pointers, structures, procedures, dynamically linked lists and much more. Experienced coders will have no problem gaining access to any of the legal OS structures or API objects and PureBasic even allows inline assembly.

https://www.purebasic.com/

**Comment by JohnBlood** [comment]
Thanks, I'll add it.
