### ISSUE TITLE
micro(A) Interpreter

### ISSUE THREAD

**Issue by aurelVZ** [JohnBlood/awesome-basic#5]
Hello John
If you have time look on my basic dialect called micro(A)
IDE + interpreter
https://github.com/aurelVZ/microA-programming-language

and community forum is on:
http://basic4all.epizy.com/index.php

**Comment by hgntn** [comment]
I added your BASIC dialect to my list:

https://github.com/hgntn/awesome-basic-dialects/commit/cc4a57d6f01e22b9ceb101ec76f519cafd8f3393

**Comment by JohnBlood** [comment]
Added
