### ISSUE TITLE
Are you still maintaining this list?

### ISSUE THREAD

**Issue by hgntn** [JohnBlood/awesome-basic#7]
I made a PR. It took many months without any actions from you so my friend, the repository owner can't wait and deleted the repo, thus closed the PR: https://github.com/JohnBlood/awesome-basic/pull/6

I made an updated list of BASIC dialects based on your list:

https://github.com/hgntn/awesome-basic-dialects

My list only cares about BASIC dialects, other things like IDEs and tutorials are not covered.

@JohnBlood Please tell us if you are still maintaining this list. Thank you.

**Comment by JohnBlood** [comment]
@hgntn I've been very busy lately, but I intent to maintain this list. I didn't see a notification about your PR, otherwise I probably would have added it. If you want to recreate it, I will take a look at it.

**Comment by hgntn** [comment]
> @hgntn I've been very busy lately, but I intent to maintain this list. I didn't see a notification about your PR, otherwise I probably would have added it. If you want to recreate it, I will take a look at it.

I'm not gonna to comply with this requirement, so sorry. When I made the PR, I didn't know there is such a requirement.

https://github.com/JohnBlood/awesome-basic/blob/master/CONTRIBUTING.md

> Make an individual pull request for each suggestion.

I added BASIC dialects in batch. An individual pull request for each suggestion (each BASIC dialect)? Impossible!

**Comment by JohnBlood** [comment]
@hgntn You can ignore that requirement. I copied that document from another awesome list.

**Comment by hgntn** [comment]
> @hgntn You can ignore that requirement. I copied that document from another awesome list.

https://github.com/JohnBlood/awesome-basic/pull/8

**Comment by JohnBlood** [comment]
Merged.
